# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='headline',
            field=models.TextField(default='', unique=True),
        ),
    ]
